var first_name = "Alyssa";
console.log(first_name);
var last_name = "Carson";
console.log(last_name);
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = 20;
console.log(a);
var b = 9;
console.log(b);
var add = a + b;
console.log(add);
